#Docker install tasks
- name: Installeer docker dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Voeg GPG key toe
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Voeg docker repo toe aan apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu noble stable
    state: present

- name: Installeer docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Start en enable docker
  systemd:
    name: docker
    enabled: true
    state: started

